// <auto-generated />
using AplikacijaZaHotel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplikacijaZaHotel.Migrations
{
    [DbContext(typeof(AplikacijaZaHotelContext))]
    partial class AplikacijaZaHotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AplikacijaZaHotel.Models.Soba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojSobe")
                        .HasColumnType("int");

                    b.Property<int>("VrstaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("BrojSobe");

                    b.HasIndex("VrstaID");

                    b.ToTable("Soba");
                });

            modelBuilder.Entity("AplikacijaZaHotel.Models.Vrsta", b =>
                {
                    b.Property<int>("VrstaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Balkon")
                        .HasColumnType("bit");

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VrstaId");

                    b.ToTable("Vrsta");
                });

            modelBuilder.Entity("AplikacijaZaHotel.Models.Soba", b =>
                {
                    b.HasOne("AplikacijaZaHotel.Models.Vrsta", "Vrsta")
                        .WithMany("Sobas")
                        .HasForeignKey("VrstaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
